### ISSUE TITLE
An formatting error occurs when the linefeed character is set to LF

### ISSUE THREAD

**Issue by chazwize** [felixfbecker/vscode-php-intellisense#121]
item | version
------------ | -------------
os | ubuntu 16.04
vscode | 1.12.2
node | 6.10.2
vscode-php-intelisense | 1.2.1

## php code
```
<?php
class Test
{
    public function testfunc ()
    {
        echo 'test';
    }
}
```

## test case
case1 . newline character LF is error
case2 . newline character CRLF is success

## error log

```
Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/PhpDocument.php(233): LanguageServer\Formatter::format('<?php\nclass VTe...', 'file:///home/ch...')
#1 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(179): LanguageServer\PhpDocument->getFormattedText()
#2 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /home/chazwize/.vscode/extensions/felixfbecker.php-intellisense-1.2.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

thanks..

**Comment by felixfbecker** [comment]
what do you mean with that? the newline characters in the file, the setting in vscode, the setting in CodeSniffer, ...?

**Comment by chazwize** [comment]
@felixfbecker newline is vscode setting

![image](https://cloud.githubusercontent.com/assets/26054516/26143919/e90e9e2e-3b21-11e7-859b-ba7f29d54714.png)
