### ISSUE TITLE
Server initialization failed.   

### ISSUE THREAD

**Issue by Friend007** [felixfbecker/vscode-php-intellisense#125]
Hello.

I try to use php-intellisense  but have error 

```
[Error - 3:45:13 PM] Server initialization failed.
  Message: UnexpectedValueException: RecursiveDirectoryIterator::__construct(c:/Users/USER.USER\AppData\Local\Application Data,c:/Users/USER.USER\AppData\Local\Application Data): Access is denied. (code: 5) in C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('c:/Users/USER...', 4128)
#1 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('c:/Users/USER...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->next()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\user.user\.vscode\extensions\felixfbecker.php-intellisense-1.3.0\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#14 {main}
  Code: -32603
```

Any Ideas? 

Thank you

**Comment by jens1o** [comment]
The php user has not the significant permissions to read the cache. Check that the php user can read and modify the dir `c:/Users/USER.USER\AppData\Local\Application Data`

**Comment by Friend007** [comment]
Hi Jens1o
From Microsoft site :
Application Data is not an actual folder, it is a Junction which is only there for backward compatibility. A Junction is a shortcut that redirects files and programs to a different location.

This particular Junction points to the  C:Users\username\AppData\Roaming folder.
My  Roaming folder has  Security setting Full control for
SYSTEM
User
Administrator

Thank you for your time :)

**Comment by felixfbecker** [comment]
What folder did you open VS Code in?

**Comment by Friend007** [comment]
C:\Program Files (x86)\Microsoft VS Code

**Comment by felixfbecker** [comment]
I mean, what folder did you open in VS Code?

**Comment by Friend007** [comment]
Ubuntu server  /var/www/html/project

**Comment by felixfbecker** [comment]
wait, I thought you are on Windows?

**Comment by Friend007** [comment]
Yes. I am on windows.  Bat server on Ubuntu I connect with mobaxterm (http://mobaxterm.mobatek.net) and use VC as default text editor for this application

**Comment by felixfbecker** [comment]
What's important is what folder path is opened inside VS Code. I.e. what is in the title bar, the explorer title, what path you get when you right click > copy path on files or tabs.

**Comment by Friend007** [comment]
Not clear understand your question but maybe this image will help
![capture](https://user-images.githubusercontent.com/22018123/27199542-65a66be6-51e4-11e7-97d4-892a2e123bd3.JPG)
.

**Comment by felixfbecker** [comment]
Could you please right click on a file and select "highlight in explorer" or "copy path" and paste the path here?

**Comment by Friend007** [comment]
C:\Users\KONSTA~1.MIL\DOCUME~1\MobaXterm\slash\RemoteFiles\1639868_2_36\table1.php

**Comment by felixfbecker** [comment]
Yeah no idea. I cannot reproduce this so don't know to help you.

**Comment by Friend007** [comment]
Thank you, Felix.  Will works without php-intellisense  :)
