### ISSUE TITLE
Request textDocument/formatting failed

### ISSUE THREAD

**Issue by Caffeineli** [felixfbecker/vscode-php-intellisense#157]
When highlighting code within a .php file on VS Code and selecting "Format Document", the following output occurs:
```
[Error - 10:44:23 AM] Request textDocument/formatting failed.
  Message: Error: Call to undefined function PHP_CodeSniffer\simplexml_load_string() in /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/squizlabs/php_codesniffer/src/Ruleset.php:161
Stack trace:
#0 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/Formatter.php(48): PHP_CodeSniffer\Ruleset->__construct(Object(PHP_CodeSniffer\Config))
#1 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\r\n\r\n\r\n\r\nre...', 'file:///home/us...')
#2 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/src/Server/TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#3 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#4 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#5 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#6 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#7 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#8 /home/user/.vscode/extensions/felixfbecker.php-intellisense-1.5.1/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#9 {main}
  Code: -32603
```
PHP version:
```
PHP 7.0.24-1+ubuntu17.04.1+deb.sury.org+1 (cli) (built: Sep 28 2017 16:21:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.24-1+ubuntu17.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
```
System:
Ubuntu Desktop 17.04

Visual Studio Code:
Version 1.16.0

**Comment by Caffeineli** [comment]
Updating VS Code to Version 16.0.1 fixes this issue.
