### ISSUE TITLE
Save code get this error massge every time, how to disable this ?

### ISSUE THREAD

**Issue by kcloze** [felixfbecker/vscode-php-intellisense#164]
ctr + s  

Save code get this error massge every time, how to disable this ?
```
[Error - 11:08:34] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\n/*\n * Th...', 'file:///media/k...')
#1 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/src/Server/TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
[Error - 11:08:35] Request textDocument/formatting failed.
  Message: Exception: Unable to format file in /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/src/Formatter.php:52
Stack trace:
#0 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/src/PhpDocument.php(179): LanguageServer\Formatter::format('<?php\n\n/*\n * Th...', 'file:///media/k...')
#1 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/src/Server/TextDocument.php(172): LanguageServer\PhpDocument->getFormattedText()
#2 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#3 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#4 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#5 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#6 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#7 /home/kcloze/.vscode/extensions/felixfbecker.php-intellisense-1.5.2/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#8 {main}
  Code: -32603 
```

**Comment by felixfbecker** [comment]
Disable format on save.
