### ISSUE TITLE
Exception when typing variable name

### ISSUE THREAD

**Issue by Joey79100** [felixfbecker/vscode-php-intellisense#293]
Hi,

For some reason, my VS Code had the extension engine crashing this morning. It asked me if I wanted to restart, and now, even after restarting VSCode, every time I start typing a variable name in any PHP file (the `$` character followed by at least one character), the output window shows up and something like this appears:

```
[Error - 12:00:55] Request textDocument/completion failed.
  Message: TypeError: strpos() expects parameter 1 to be string, null given in C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\src\CompletionProvider.php:532
Stack trace:
#0 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\src\CompletionProvider.php(532): strpos(NULL, 'a')
#1 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\src\CompletionProvider.php(519): LanguageServer\CompletionProvider->isAssignmentToVariableWithPrefix(Object(Microsoft\PhpParser\Node\Expression\AssignmentExpression), 'a')
#2 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\src\CompletionProvider.php(458): LanguageServer\CompletionProvider->findVariableDefinitionsInNode(Object(Microsoft\PhpParser\Node\Statement\ExpressionStatement), 'a')
#3 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\src\CompletionProvider.php(215): LanguageServer\CompletionProvider->suggestVariablesAtNode(Object(Microsoft\PhpParser\Node\Expression\Variable), 'a')
#4 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\src\Server\TextDocument.php(369): LanguageServer\CompletionProvider->provideCompletion(Object(LanguageServer\PhpDocument), Object(LanguageServer\Protocol\Position), NULL)
#5 [internal function]: LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}()
#6 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\sabre\event\lib\coroutine.php(70): Generator->send(Object(LanguageServer\PhpDocument))
#7 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(Object(LanguageServer\PhpDocument))
#8 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#9 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#10 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#11 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#12 C:\Users\jq\.vscode\extensions\felixfbecker.php-intellisense-2.3.1\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#13 {main}
  Code: -32603
```

I'm not sure if it is coming from the extension itself or its integration into VSCode, nor I know what caused the initial crash, so I'm posting this here in case it's the right place.

**Comment by Joey79100** [comment]
Uhm, we're a few days later, and I've just realized the issue has disappeared by itself. I wouldn't even be able to tell what did it, maybe just the fact that the computer has rebooted since then, but I don't remember when it stopped.
