### ISSUE TITLE
PHP Language Server server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by hkm-mo** [felixfbecker/vscode-php-intellisense#36]
After updated version 0.0.12, I always got error.

> The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

![screen shot 2016-11-21 at 10 46 56 am](https://cloud.githubusercontent.com/assets/2552495/20469110/5e23af90-afd8-11e6-85c6-e84ad4ffa3d1.png)

Another message found in the console:

```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Users/user/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/nikic/php-parser/lib/PhpParser/NodeAbstract.php on line 97
PHP Stack trace:
PHP   1. {main}() /Users/user/.vscode/extensions/felixfbecker.php-intellisense-0.0.12/vendor/felixfbecker/language-server/bin/php-language-server.php:0
...
PHP 228. PhpParser\NodeTraverser->traverseArray()
PHP 242. PhpParser\NodeTraverser->traverseNode()
PHP 249. PhpParser\NodeTraverser->traverseArray()
PHP 254. LanguageServer\NodeVisitor\DocBlockParser->enterNode()
```

**Comment by felixfbecker** [comment]
Increase `xdebug.max_nesting_level` (or even better, don't run the language server with XDebug enabled, it impacts performance)

**Comment by tungvn** [comment]
I got this error, in v0.0.12

My stack trace:
```
[Extension Host] UnexpectedValueException: RecursiveDirectoryIterator::__construct(e:/Project/dmdc\manage-category\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-modules-amd\node_modules\babel-template\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\escape-string-regexp,e:/Project/dmdc\manage-category\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-modules-amd\node_modules\babel-template\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\escape-string-regexp): The system cannot find the path specified. (code: 3) in C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('e:/Project/dmdc...', 4128)
#1 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('e:/Project/dmdc...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\felixfbecker\language-server\src\LanguageServer.php(234): IteratorIterator->next()
#6 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#7 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\Administrator\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\felixfbecker\language-server\bin\php-language-server.php(51): Sabre\Event\Loop\run()
#14 {main}A.logExtensionHostMessage @ extensionHost.ts:293
extensionHost.ts:293 [Extension Host] PHP process disconnected
```

**Comment by felixfbecker** [comment]
See https://github.com/felixfbecker/php-language-server/issues/113

**Comment by tungvn** [comment]
Yep, I tried to upgrade npm to v4.1.1 and fixed this bug!

**Comment by saidbakr** [comment]
How could I get that stack trace?
