### ISSUE TITLE
Option to point to language server install location

### ISSUE THREAD

**Issue by TheColorRed** [felixfbecker/vscode-php-intellisense#41]
I cannot install the language server in my current project (nor do I want to) because it conflicts with laravel's install. I would like to be able to point to the install location of the language server through a config setting, but this doesn't seem to be supported.

I can install it somewhere else and run it through a seperate terminal, but this is undesired.

```
 composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install laravel/framework v5.2.45
    - Conclusion: don't install laravel/framework v5.2.44
    - Conclusion: don't install laravel/framework v5.2.43
    - Conclusion: don't install laravel/framework v5.2.42
    - Conclusion: don't install laravel/framework 5.2.41
    - Conclusion: don't install laravel/framework v5.2.40
    - Conclusion: don't install laravel/framework v5.2.39
    - Conclusion: don't install laravel/framework v5.2.38
    - Conclusion: don't install laravel/framework v5.2.37
    - Conclusion: don't install laravel/framework v5.2.36
    - Conclusion: don't install laravel/framework v5.2.35
    - Conclusion: don't install laravel/framework v5.2.34
    - Conclusion: don't install laravel/framework v5.2.33
    - Conclusion: don't install laravel/framework v5.2.32
    - Conclusion: don't install laravel/framework v5.2.31
    - Conclusion: don't install laravel/framework v5.2.30
    - Conclusion: don't install laravel/framework v5.2.29
    - Conclusion: don't install laravel/framework v5.2.28
    - Conclusion: don't install laravel/framework v5.2.27
    - Conclusion: don't install laravel/framework v5.2.26
    - Conclusion: don't install laravel/framework v5.2.25
    - Conclusion: don't install laravel/framework v5.2.24
    - Conclusion: don't install laravel/framework v5.2.23
    - Conclusion: don't install laravel/framework v5.2.22
    - Conclusion: don't install laravel/framework v5.2.21
    - Conclusion: don't install laravel/framework v5.2.20
    - Conclusion: don't install laravel/framework v5.2.19
    - Conclusion: don't install laravel/framework v5.2.18
    - Conclusion: don't install laravel/framework v5.2.17
    - Conclusion: don't install laravel/framework v5.2.16
    - Conclusion: don't install laravel/framework v5.2.15
    - Conclusion: don't install laravel/framework v5.2.14
    - Conclusion: don't install laravel/framework v5.2.13
    - Conclusion: don't install laravel/framework v5.2.12
    - Conclusion: don't install laravel/framework v5.2.11
    - Conclusion: don't install laravel/framework v5.2.10
    - Conclusion: don't install laravel/framework v5.2.9
    - Conclusion: don't install laravel/framework v5.2.8
    - Conclusion: don't install laravel/framework v5.2.7
    - Conclusion: don't install laravel/framework v5.2.6
    - Conclusion: don't install laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.4
    - Conclusion: don't install laravel/framework v5.2.3
    - Conclusion: don't install laravel/framework v5.2.2
    - Conclusion: don't install laravel/framework v5.2.1
    - laravel/framework v5.2.0 requires psy/psysh 0.6.* -> satisfiable by psy/psysh[v0.6.0, v0.6.1].
    - Conclusion: don't install psy/psysh v0.6.1
    - Conclusion: don't install nikic/php-parser v3.0.1|don't install psy/psysh v0.6.0|install nikic/php-parser v2.1.1
    - Conclusion: don't install nikic/php-parser v2.1.1
    - Installation request for laravel/framework 5.2.* -> satisfiable by laravel/framework[5.2.41, v5.2.0, v5.2.1, v5.2.10, v5.2.11, v5.2.12, v5.2.13, v5.2.14, v5.2.15, v5.2.16, v5.2.17, v5.2.18, v5.2.19, v5.2.2, v5.2.20, v5.2.21, v5.2.22, v5.2.23, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.29, v5.2.3, v5.2.30, v5.2.31, v5.2.32, v5.2.33, v5.2.34, v5.2.35, v5.2.36, v5.2.37, v5.2.38, v5.2.39, v5.2.4, v5.2.40, v5.2.42, v5.2.43, v5.2.44, v5.2.45, v5.2.5, v5.2.6, v5.2.7, v5.2.8, v5.2.9].
    - Installation request for felixfbecker/language-server ^3.1 -> satisfiable by felixfbecker/language-server[v3.1.0].
    - psy/psysh v0.6.0 requires nikic/php-parser ^1.2.1|~2.0 -> satisfiable by nikic/php-parser[v1.2.1, v1.2.2, v1.3.0, v1.4.0, v1.4.1, v2.0.0, v2.0.1, v2.1.0, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.0.0, v1.2.1].
    - Can only install one of: nikic/php-parser[v3.0.0, v1.2.2].
    - Can only install one of: nikic/php-parser[v3.0.0, v1.3.0].
    - Can only install one of: nikic/php-parser[v3.0.0, v1.4.0].
    - Can only install one of: nikic/php-parser[v3.0.0, v1.4.1].
    - Can only install one of: nikic/php-parser[v3.0.0, v2.0.0].
    - Can only install one of: nikic/php-parser[v3.0.0, v2.0.1].
    - Can only install one of: nikic/php-parser[v3.0.0, v2.1.0].
    - felixfbecker/language-server v3.1.0 requires nikic/php-parser ^3.0.0beta2 -> satisfiable by nikic/php-parser[v3.0.0, v3.0.1, v3.0.2].
    - Conclusion: don't install nikic/php-parser v3.0.2
```

**Comment by felixfbecker** [comment]
Don't understand your issue. The language server is bundled with the extension, you don't need to install it manually.

**Comment by TheColorRed** [comment]
Hmm okay... when I run it I get the following messages:

```
[Info  - 11:52:52 AM] Connection to server got closed. Server will restart.
[Info  - 11:52:57 AM] Connection to server got closed. Server will restart.
[Info  - 11:53:02 AM] Connection to server got closed. Server will restart.
[Info  - 11:53:08 AM] Connection to server got closed. Server will restart.
[Error - 11:53:13 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by felixfbecker** [comment]
There should be a stack trace in Help > Toggle developer tools

**Comment by TheColorRed** [comment]
```
extensionHost.ts:255 [Extension Host] UnexpectedValueException: RecursiveDirectoryIterator::__construct(c:/Users/rnaddy/Documents/www/gamesmart\node_modules\laravel-elixir\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi,c:/Users/rnaddy/Documents/www/gamesmart\node_modules\laravel-elixir\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-block-scoping\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\chalk\node_modules\strip-ansi): The system cannot find the path specified. (code: 3) in C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('c:/Users/rnaddy...', 4128)
#1 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('c:/Users/rnaddy...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\felixfbecker\language-server\src\LanguageServer.php(234): IteratorIterator->next()
#6 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#7 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\rnaddy\.vscode\extensions\felixfbecker.php-intellisense-0.0.12\vendor\felixfbecker\language-server\bin\php-language-server.php(51): Sabre\Event\Loop\run()
#14 {main}I.logExtensionHostMessage @ extensionHost.ts:255I.onMessaage @ extensionHost.ts:196(anonymous function) @ extensionHost.ts:141emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:255 [Extension Host] PHP process disconnected
```

![php-language-server](https://cloud.githubusercontent.com/assets/1571806/21111835/fce36df0-c068-11e6-9e51-06915e4de8ee.PNG)

**Comment by felixfbecker** [comment]
See this issue https://github.com/felixfbecker/php-language-server/issues/113
