### ISSUE TITLE
PHP Language Server Output window re-opens after being manually closed

### ISSUE THREAD

**Issue by jjarolim** [felixfbecker/vscode-php-intellisense#461]
Hi felix -

It seems that the issue in #65 is not really solved or popped up again after an update. Lots of new comments there on the closed issue - maybe worth a look: thanks!

Best from Salzburg,

- Johannes

**Comment by roelvanhintum** [comment]
Solved by setting the following inside settings.json:
```
"php.revealOutputChannelOn": "never"
```

**Comment by gszy** [comment]
#454 was merged, does the problem still occur in version 2.3.14?

**Comment by Korben85** [comment]
still exists in 2.3.14
ErrorException: Method ReflectionParameter::getClass() is deprecated in C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php:241
Stack trace:
#0 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', 'C:\\Users\\thombr...', 241)
#1 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(198): phpDocumentor\Reflection\DocBlock\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array)
#2 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlock\StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDocumentor\Reflection\Types\Context))
#3 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlockFactory.php(231): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@param ClientCa...', Object(phpDocumentor\Reflection\Types\Context))
#4 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\phpdocumentor\reflection-docblock\src\DocBlockFactory.php(96): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@param ClientCa...', Object(phpDocumentor\Reflection\Types\Context))
#5 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\advanced-json-rpc\lib\Dispatcher.php(98): phpDocumentor\Reflection\DocBlockFactory->create('/**\n     * The ...', Object(phpDocumentor\Reflection\Types\Context))
#6 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\LanguageServer.php(131): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#7 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#8 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\coroutine.php(64): Generator->valid()
#9 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\coroutine.php(118): Sabre\Event\{closure}()
#10 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\LanguageServer.php(154): Sabre\Event\coroutine(Object(Closure))
#11 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Message))
#12 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\src\ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#13 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#14 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#15 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#16 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#17 C:\Users\username\.vscode\extensions\felixfbecker.php-intellisense-2.3.14\vendor\felixfbecker\language-server\bin\php-language-server.php(55): Sabre\Event\Loop\run()
#18 {main}
