### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ShalvexNovachrono** [felixfbecker/vscode-php-intellisense#528]
- Issue Type: `Bug`
- Extension Name: `php-intellisense`
- Extension Version: `2.3.14`
- OS Version: `Windows_NT ia32 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7865,
		"activateCallTime": 761,
		"activateResolvedTime": 16811,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "felixfbecker.php-intellisense",
				"_lower": "felixfbecker.php-intellisense"
			},
			"activationEvent": "workspaceContainsTimeout:**/*.php"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "ErrorException: Method ReflectionParameter::getClass() is deprecated in C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php:241\nStack trace:\n#0 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', 'C:\\\\Users\\\\majun\\\\...', 241)\n#1 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php(198): phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array)\n#2 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php(122): phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDocumentor\\Reflection\\Types\\Context))\n#3 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlockFactory.php(231): phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory->create('@param ClientCa...', Object(phpDocumentor\\Reflection\\Types\\Context))\n#4 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlockFactory.php(96): phpDocumentor\\Reflection\\DocBlockFactory->parseTagBlock('@param ClientCa...', Object(phpDocumentor\\Reflection\\Types\\Context))\n#5 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\advanced-json-rpc\\lib\\Dispatcher.php(98): phpDocumentor\\Reflection\\DocBlockFactory->create('/**\\n     * The ...', Object(phpDocumentor\\Reflection\\Types\\Context))\n#6 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\src\\LanguageServer.php(131): AdvancedJsonRpc\\Dispatcher->dispatch(Object(AdvancedJsonRpc\\Request))\n#7 [internal function]: LanguageServer\\LanguageServer->LanguageServer\\{closure}()\n#8 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\coroutine.php(64): Generator->valid()\n#9 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\coroutine.php(118): Sabre\\Event\\{closure}()\n#10 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\src\\LanguageServer.php(154): Sabre\\Event\\coroutine(Object(Closure))\n#11 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\EmitterTrait.php(88): LanguageServer\\LanguageServer->LanguageServer\\{closure}(Object(LanguageServer\\Message))\n#12 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\src\\ProtocolStreamReader.php(56): Sabre\\Event\\Emitter->emit('message', Array)\n#13 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\Loop.php(311): LanguageServer\\ProtocolStreamReader->LanguageServer\\{closure}()\n#14 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\Loop.php(233): Sabre\\Event\\Loop\\Loop->runStreams(NULL)\n#15 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\Loop.php(194): Sabre\\Event\\Loop\\Loop->tick(true)\n#16 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\functions.php(122): Sabre\\Event\\Loop\\Loop->run()\n#17 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\bin\\php-language-server.php(55): Sabre\\Event\\Loop\\run()\n#18 {main}"
		},
		{
			"name": "Error",
			"message": "ErrorException: Method ReflectionParameter::getClass() is deprecated in C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php:241\nStack trace:\n#0 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', 'C:\\\\Users\\\\majun\\\\...', 241)\n#1 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php(198): phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array)\n#2 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlock\\StandardTagFactory.php(122): phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory->createTag('void', 'return', Object(phpDocumentor\\Reflection\\Types\\Context))\n#3 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlockFactory.php(231): phpDocumentor\\Reflection\\DocBlock\\StandardTagFactory->create('@return void', Object(phpDocumentor\\Reflection\\Types\\Context))\n#4 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\phpdocumentor\\reflection-docblock\\src\\DocBlockFactory.php(96): phpDocumentor\\Reflection\\DocBlockFactory->parseTagBlock('@return void', Object(phpDocumentor\\Reflection\\Types\\Context))\n#5 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\advanced-json-rpc\\lib\\Dispatcher.php(98): phpDocumentor\\Reflection\\DocBlockFactory->create('/**\\n     * The ...', Object(phpDocumentor\\Reflection\\Types\\Context))\n#6 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\src\\LanguageServer.php(131): AdvancedJsonRpc\\Dispatcher->dispatch(Object(AdvancedJsonRpc\\Request))\n#7 [internal function]: LanguageServer\\LanguageServer->LanguageServer\\{closure}()\n#8 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\coroutine.php(64): Generator->valid()\n#9 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\coroutine.php(118): Sabre\\Event\\{closure}()\n#10 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\src\\LanguageServer.php(154): Sabre\\Event\\coroutine(Object(Closure))\n#11 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\EmitterTrait.php(88): LanguageServer\\LanguageServer->LanguageServer\\{closure}(Object(LanguageServer\\Message))\n#12 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\src\\ProtocolStreamReader.php(56): Sabre\\Event\\Emitter->emit('message', Array)\n#13 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\Loop.php(311): LanguageServer\\ProtocolStreamReader->LanguageServer\\{closure}()\n#14 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\Loop.php(233): Sabre\\Event\\Loop\\Loop->runStreams(NULL)\n#15 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\Loop.php(194): Sabre\\Event\\Loop\\Loop->tick(true)\n#16 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\sabre\\event\\lib\\Loop\\functions.php(122): Sabre\\Event\\Loop\\Loop->run()\n#17 C:\\Users\\majun\\.vscode\\extensions\\felixfbecker.php-intellisense-2.3.14\\vendor\\felixfbecker\\language-server\\bin\\php-language-server.php(55): Sabre\\Event\\Loop\\run()\n#18 {main}"
		}
	]
}
```

**Comment by kierandelaney** [comment]
Duplicate of #560 (this was first but that has more conversation).
