### ISSUE TITLE
Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by kdambekalns** [felixfbecker/vscode-php-intellisense#560]
```
ErrorException: Method ReflectionParameter::getClass() is deprecated in /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php:241
Stack trace:
#0 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(241): {closure}(8192, 'Method Reflecti...', '/Users/karsten/...', 241)
#1 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(198): phpDocumentor\Reflection\DocBlock\StandardTagFactory->getArgumentsForParametersFromWiring(Array, Array)
#2 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php(122): phpDocumentor\Reflection\DocBlock\StandardTagFactory->createTag('ClientCapabilit...', 'param', Object(phpDocumentor\Reflection\Types\Context))
#3 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(231): phpDocumentor\Reflection\DocBlock\StandardTagFactory->create('@param ClientCa...', Object(phpDocumentor\Reflection\Types\Context))
#4 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/phpdocumentor/reflection-docblock/src/DocBlockFactory.php(96): phpDocumentor\Reflection\DocBlockFactory->parseTagBlock('@param ClientCa...', Object(phpDocumentor\Reflection\Types\Context))
#5 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/advanced-json-rpc/lib/Dispatcher.php(98): phpDocumentor\Reflection\DocBlockFactory->create('/**\n     * The ...', Object(phpDocumentor\Reflection\Types\Context))
#6 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/src/LanguageServer.php(131): AdvancedJsonRpc\Dispatcher->dispatch(Object(AdvancedJsonRpc\Request))
#7 [internal function]: LanguageServer\LanguageServer->LanguageServer\{closure}()
#8 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/coroutine.php(64): Generator->valid()
#9 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/coroutine.php(118): Sabre\Event\{closure}()
#10 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/src/LanguageServer.php(154): Sabre\Event\coroutine(Object(Closure))
#11 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/EmitterTrait.php(88): LanguageServer\LanguageServer->LanguageServer\{closure}(Object(LanguageServer\Message))
#12 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/src/ProtocolStreamReader.php(56): Sabre\Event\Emitter->emit('message', Array)
#13 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/Loop.php(311): LanguageServer\ProtocolStreamReader->LanguageServer\{closure}()
#14 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/Loop.php(233): Sabre\Event\Loop\Loop->runStreams(NULL)
#15 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#16 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#17 /Users/karsten/.vscode/extensions/felixfbecker.php-intellisense-2.3.14/vendor/felixfbecker/language-server/bin/php-language-server.php(55): Sabre\Event\Loop\run()
#18 {main}
```

**Comment by c-schmitz** [comment]
Happens with PHP8.

**Comment by codeunifier** [comment]
+1

**Comment by gongwen** [comment]
+1

**Comment by AWqxKAWERbXo** [comment]
https://github.com/felixfbecker/php-language-server/issues/779 ?

**Comment by bksubramanyarao** [comment]
php 8
same issue please help

**Comment by ertugrulakca** [comment]
+1

**Comment by ertugrulakca** [comment]
this error caused by this package. 
[https://github.com/phpDocumentor/ReflectionDocBlock](https://github.com/phpDocumentor/ReflectionDocBlock) 

and this error fixed on phpdocumentor/reflection-docblock v5. need to update 4.3.2 to 5.2.2. 
https://github.com/phpDocumentor/ReflectionDocBlock/issues/264

**Comment by archergod** [comment]
Yup it is happen on php 8.0.7, on Windows 10 .

**Comment by Abromeit** [comment]
+1

**Comment by UVLabs** [comment]
Extension seems to be dead, anyone have a good alternate recommendation? I really liked this extension but it doesn't work anymore due to this error

**Comment by Krato** [comment]
Happening all time :(

**Comment by archergod** [comment]
https://marketplace.visualstudio.com/items?itemName=zobo.php-intellisense 
This will work.

**Comment by Krato** [comment]
> https://marketplace.visualstudio.com/items?itemName=zobo.php-intellisense This will work.

Yes, but how can I enable premium features with that extension?
