### ISSUE TITLE
Excluding folders from scan

### ISSUE THREAD

**Issue by codewp** [felixfbecker/vscode-php-intellisense#63]
Hello,

Thank you for this useful extension for visual studio code.

Is there any way to exclude some folders from scan, because I got below error, it seems that this extension search node_modules folder too, so I think that excluding this folder from search can help us.

```javascript
[Error - 11:47:13 PM] Server initialization failed.
  Message: UnexpectedValueException: RecursiveDirectoryIterator::__construct(c:/xampp/htdocs/axent/wp-content/plugins/wc-multistep-designer\node_modules\grunt-contrib-cssmin\node_modules\maxmin\node_modules\pretty-bytes\node_modules\meow\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\strip-bom,c:/xampp/htdocs/axent/wp-content/plugins/wc-multistep-designer\node_modules\grunt-contrib-cssmin\node_modules\maxmin\node_modules\pretty-bytes\node_modules\meow\node_modules\read-pkg-up\node_modules\read-pkg\node_modules\load-json-file\node_modules\strip-bom): The system cannot find the path specified. (code: 3) in C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php:43
Stack trace:
#0 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(43): RecursiveDirectoryIterator->__construct('c:/xampp/htdocs...', 4128)
#1 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\webmozart\glob\src\Iterator\RecursiveDirectoryIterator.php(55): Webmozart\Glob\Iterator\RecursiveDirectoryIterator->__construct('c:/xampp/htdocs...', 4128)
#2 [internal function]: Webmozart\Glob\Iterator\RecursiveDirectoryIterator->getChildren()
#3 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\webmozart\glob\src\Iterator\RegexFilterIterator.php(130): FilterIterator->next()
#4 [internal function]: Webmozart\Glob\Iterator\RegexFilterIterator->next()
#5 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\felixfbecker\language-server\src\FilesFinder\FileSystemFilesFinder.php(24): IteratorIterator->next()
#6 [internal function]: LanguageServer\FilesFinder\FileSystemFilesFinder->LanguageServer\FilesFinder\{closure}()
#7 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\sabre\event\lib\coroutine.php(70): Generator->send(NULL)
#8 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\sabre\event\lib\Promise.php(242): Sabre\Event\{closure}(NULL)
#9 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\sabre\event\lib\Loop\Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#10 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\sabre\event\lib\Loop\Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#11 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\sabre\event\lib\Loop\Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#12 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\sabre\event\lib\Loop\functions.php(122): Sabre\Event\Loop\Loop->run()
#13 C:\Users\taher\.vscode\extensions\felixfbecker.php-intellisense-1.0.0\vendor\felixfbecker\language-server\bin\php-language-server.php(50): Sabre\Event\Loop\run()
#14 {main}
  Code: -32603 
```

Please let me know is there anyway to fixing this issue?

Regards.

**Comment by felixfbecker** [comment]
Please search for an existing issue before opening a new one.
https://github.com/felixfbecker/php-language-server/issues?utf8=%E2%9C%93&q=is%3Aissue%20node_modules
