### ISSUE TITLE
Extension doesn't work correctly

### ISSUE THREAD

**Issue by zRnatoNeto** [felixfbecker/vscode-php-intellisense#97]
When I try to format the code, this error appears:

![format](https://cloud.githubusercontent.com/assets/16787161/24078106/aa830a40-0c42-11e7-9ecc-d2576b1874ea.gif)
```
[Error - 1:15:24 AM] Request textDocument/formatting failed.
  Message: Error: Call to undefined function PHP_CodeSniffer\simplexml_load_string() in /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/squizlabs/php_codesniffer/src/Ruleset.php:161
Stack trace:
#0 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/Formatter.php(48): PHP_CodeSniffer\Ruleset->__construct(Object(PHP_CodeSniffer\Config))
#1 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/PhpDocument.php(233): LanguageServer\Formatter::format('<?php\n\nnamespac...', 'file:///opt/lam...')
#2 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/src/Server/TextDocument.php(179): LanguageServer\PhpDocument->getFormattedText()
#3 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Promise.php(242): LanguageServer\Server\TextDocument->LanguageServer\Server\{closure}(Object(LanguageServer\PhpDocument))
#4 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/Loop.php(261): Sabre\Event\Promise->Sabre\Event\{closure}()
#5 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/Loop.php(215): Sabre\Event\Loop\Loop->runNextTicks()
#6 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/Loop.php(194): Sabre\Event\Loop\Loop->tick(true)
#7 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/sabre/event/lib/Loop/functions.php(122): Sabre\Event\Loop\Loop->run()
#8 /home/rnato/.vscode/extensions/felixfbecker.php-intellisense-1.1.3/vendor/felixfbecker/language-server/bin/php-language-server.php(102): Sabre\Event\Loop\run()
#9 {main}
  Code: -32603
```

And completion:

![autocomplete](https://cloud.githubusercontent.com/assets/16787161/24078109/ccf1e632-0c42-11e7-8f03-ebbfa7ef5a60.gif)

That is, nothing is working, nor "Go to definition".
What's happening?

**Comment by jens1o** [comment]
Did you install the simple_xml extension for php? You need it, and it should be there when you didn't modify any build parameters. How did you installed php? @zRnatoNeto

**Comment by felixfbecker** [comment]
Closing because no response
